In [3]:
import torch
x = torch.arange(24).reshape(2, 3, 4)
print(x.shape)
print(x)

torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [4]:
y = x.transpose(1, 2)
print(y.shape)
print(y)

torch.Size([2, 4, 3])
tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])


In [6]:
z = x.transpose(0, 1)
print(z.shape)
print(z)

torch.Size([3, 2, 4])
tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]])


In [3]:
import torch

bs, seq_len, vocab = 2, 4, 10
x = torch.randn(bs, seq_len, vocab)
print(x.shape)

indices = torch.randint(0, vocab, (bs, seq_len, 3))

y = torch.gather(x, 2, indices)
print(y.shape)

torch.Size([2, 4, 10])
torch.Size([2, 4, 3])
